### ISSUE TITLE
minor issue with the hook

### ISSUE THREAD

**Issue by kerroncheddie** [clearkimura/Customizer#1]
if [ ! -e "$HOOK" ];then
    ERROR_MESSAGE "The hook files doesn't exists"
else
    cp -f "$HOOK" "$WORK_DIR/FileSystem/tmp/HOOK"
fi

**allow_local_X_access**
**mount_sys**
**mount_dbus**

**chroot** "chmod +x /tmp/HOOK
bin/sh /tmp/HOOK"

**umount_sys**
**recursive_umount**
**block_local_X_access**

and there is no need for basename

**Comment by fluxer** [comment]
Ok, thanks for the first suggestion. 

Using "exec /tmp/HOOK" will ensure that no additional shell is spawned if it is not needed, image if the hook is Python, Perl script or even binary file, then exec is more appropriate way to execute it as long as there is shebang in it (if it is script).

Thanks for the input anyway ;)
