### ISSUE TITLE
does not install on mini-remix

### ISSUE THREAD

**Issue by bmix** [clearkimura/Customizer#10]
Hi,

tonight I got the ubuntu-mini-remix installed on a VM and tried both installation methods as outlined in 2.2.1 and 2.2.2 (method 1, method 2 did not function due to ownership problems, I did sudo but I could not get write access to the path, no clue what's going on there).

2.2.1 here is what happens: first this: http://d.pr/i/CMJ4 then this: http://d.pr/i/EaN0

2.2.2 (method 1) errors out with the notice, that no network connection could be established. Which is strange, since I can connect from the VM to the internet. Method 2 fails due to permissions (I am aware, that LINK and RELEASE needs to be replaced on the echo instruction, but that would not change the problem), see both here: http://d.pr/i/pbmJ

Now my problems with 2.2.2 are clearly beyond Customizer's influence (seems the VM is messed up, though it was a clean install) 2.2.1 should be fixable, no?

Thans a lot!

**Comment by ghost** [comment]
Dear user,

First of all, you must aware that Ubuntu MIni Remix is _not_ a
full-featured LiveCD.

You can use it to install on VM or local machine, yes, but almost
nothing is useful by default.

Read their wiki FAQ on the following page:
  https://answers.launchpad.net/ubuntu-mini-remix/+faq/35

Next, errors in your first two screenshots proves that
ubuntu-mini-remix does not have required repository enabled by
default, hence you got errors "E: Unable to locate packages.."

To solve this, you must enable 'Universe' repository to install
gambas2-\* packages.

Refer to our manual, under subchapter 2.1, as follows.
  https://docs.google.com/document/d/1PfhHnSBjv-IDI7Yh5obhMGYCAV9Gw1NPEynU4GqKTsA/edit?pli=1#heading=h.u8u8wokw9qa8

In short, you can't use ubuntu-mini-remix the same as regular distributions.

This means whatever unofficial or community repository packages,
including Customizer, _cannot_ be installed on ubuntu-mini-remix. And
Customizer has nothing wrong to do with this issue.

Hope these explanations are made clear to you.

On 7 July 2012 15:41, Andreas M.
reply@reply.github.com
wrote:

> Hi,
> 
> tonight I got the ubuntu-mini-remix installed on a VM and tried both installation methods as outlined in 2.2.1 and 2.2.2 (method 1, method 2 did not function due to ownership problems, I did sudo but I could not get write access to the path, no clue what's going on there).
> 
> 2.2.1 here is what happens: first this: http://d.pr/i/CMJ4 then this: http://d.pr/i/EaN0
> 
> 2.2.2 (method 1) errors out with the notice, that no network connection could be established. Which is strange, since I can connect from the VM to the internet. Method 2 fails due to permissions (I am aware, that LINK and RELEASE needs to be replaced on the echo instruction, but that would not change the problem), see both here: http://d.pr/i/pbmJ
> 
> Now my problems with 2.2.2 are clearly beyond Customizer's influence (seems the VM is messed up, though it was a clean install) 2.2.1 should be fixable, no?
> 
> Thans a lot!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fluxer/Customizer/issues/10

## 

MUBIIN
clearkimura@gmail.com

**Comment by fluxer** [comment]
@clearkimura I see no reason why Customizer cannot be installed/used on UMR, if the proper repositories are enabled everything should be fine because UMR is just a minimal Ubuntu Live CD image but packages are not changed, they are provided as they are  by the Ubuntu devs.

@bmix You probably don't follow the instructions properly. Do you read all of it (section 2) and then executing the commands or you just copy-paste-pray-it-works because if you don't think what those do I can put `sudo rm -rf /` and guess what happens :). Also I see that just when Git was supposed to be installed you hit Ctrl+C and interrupted it.

Another things is that you'd better provide logs, just use `command | tee logfile.txt` and upload the file somewhere (there are utils with the purpose of doing this from CLI).
