### ISSUE TITLE
Customizer identifies Ubuntu server as invalid disk

### ISSUE THREAD

**Issue by hrasadi** [clearkimura/Customizer#12]
I am using v3.2.3 and when I try to mount ubuntu-server 12.04, Customizer claims that it's not a valid ISO image. Is there any clues how I can work this around?

**Comment by fluxer** [comment]
There is a workaround for everything but it's not a good thing to force Customizer use ISO image that at later stage can not be build for an example.

There is a brief info about why some of the Ubuntu (and derivatives) ISO images don't work, just take a look [here](http://sourceforge.net/apps/phpbb/u-customizer/viewtopic.php?f=1&t=10&start=0#supported_isos). And a quick google query will take you to [this](http://samiux.wordpress.com/2009/03/19/the-different-between-ubuntu-desktop-alternate-cd-and-server-cd/).

Please read the documentation carefully and if something is not clear enough you are welcome to edit the Wiki here on GitHub.

All-in-all: Customizer was never supporting this type of ISO images, workaround - fork Customizer and make it do so if you wish but bare in mind that it can not just be patched, you must re-write it to make it work with those. Good Luck!
