### ISSUE TITLE
Support alternate Ubuntu ISOs

### ISSUE THREAD

**Issue by kovica** [clearkimura/Customizer#15]
With Ubuntu you can download two ISOs:
- desktop
- alternate

Alternate is meant to create automated installs.
I use it in my company to do just that.

When I open alternate ISO with Customizer I get:
[_] Executing extract at: 01:43:42/01-10-2012
[_] Creating work directories
[_] Mounting ISO
[_] Checking ISO image
[X] This is not a usable ISO image

**Comment by ghost** [comment]
@kovica 
Only Live CD is supported by Customizer. Alternative ISO images are _not_ supported.
I noticed our FAQ has missing text to explain this clearly. My apologies for inconveniences.

@fluxer 
The part of FAQ which explains "alternative images are not supported" has been missing.
I'll revise FAQ accordingly. My bad.

**Comment by ghost** [comment]
@kovica @fluxer 
The FAQ page has been updated. See "What ISO images are supported by Customizer?"
 at https://github.com/fluxer/Customizer/wiki/FAQ

**Comment by fluxer** [comment]
Ok, cool.

**Comment by ghost** [comment]
@kovica 
Final answers as below.

Short answer: Customizer is a tool for customizing Live CD (compressed image and bootable) and Ubuntu Mini Remix (which is also a compressed image, except _not_ bootable by default).

Long answer: Customizer cannot customize alternate ISO images i.e. installable package ISO. To create such image, I suggest you to look at [APTonCD](http://aptoncd.sourceforge.net/). Or, if you are interested in installing packages to your machine, by offline, without creating such ISO image file, then look at [Keyrx](http://keryxproject.org/) and [Sushi huh?](http://sushi-huh.sourceforge.net/).

If nothing else to be commented, kindly close this issue.

**Comment by kovica** [comment]
Nope, nothing else.

Thanks.
