### ISSUE TITLE
12.10 and Gamba3

### ISSUE THREAD

**Issue by thiagojedi** [clearkimura/Customizer#16]
Customizer doesn't install on Ubuntu 12.10 (and derivatives) because it depends on Gamba2 which has been replaced by Gamba3 in 12.10.

**Comment by fluxer** [comment]
2-options:
1. port it to Gambas3
2. use 3-rd party repositories which provide the Gambas2 packages for Ubuntu 12.10 (and derivatives)

I don't plan to port it so feel free to do it.
