### ISSUE TITLE
Network problem

### ISSUE THREAD

**Issue by ss4** [clearkimura/Customizer#20]
Release 3.2.3,after lubuntu 12.10 rebuild there is a partial working network connection,i can ping the router but can't go out,it seems a dns problem.

**Comment by ss4** [comment]
I have solved,manually created resolv.conf file in /etc.

**Comment by fluxer** [comment]
Lubuntu 12.10 should re-create resolv.conf on boot from what I know if it is starting a DHCP daemon, if not then it's not problem with Customizer.

However, if you can reproduce the problem by extracting the ISO and rebuilding it without any customizations then it's problem with Customizer. Can you do that for me? (I will try it myself later)

**Comment by OsdKnights** [comment]
I am customizing Ubuntu 12.10 ISO . I also encountered the same issue with the network connectivity after re-building. I was able to reproduce the error after extracting the ISO and rebuilding without any customizations

**Comment by fluxer** [comment]
@ss4 and @OsdKnights The host OS?

**Comment by ss4** [comment]
Mint 13 ubuntu based

**Comment by OsdKnights** [comment]
host - Ubuntu 12.04 64-bit
customizing image - Ubuntu 12.10 32-bit

**Comment by fluxer** [comment]
The problem is something I suspect caused by the initramfs images, those who want to investigate this further - good luck! I've tried a few things but the fact that Ubuntu is so slow and I have to run it in virtual machine makes me swear like hell.

**Comment by fluxer** [comment]
Can you test if 90225b7 fixes the issue?
