### ISSUE TITLE
installation from master branch

### ISSUE THREAD

**Issue by fluxer** [clearkimura/Customizer#21]
This issue is releated to issue #19.

The problem is that after installation with the install.sh script the GUI fails to execute with the following error as reported by OsdKnights

```
ERROR: #2: Cannot load class 'FMain': Unable to load class file
```

To avoid repeating my self I will quote here from issue #19:

> Well, installing from the gambas3 branch works fine here, I can not test the gambas2 (master) branch since I'm running Debian Wheezy and Gambas2 packages are not available for it (at least from the official repositories). Thus, I'm waiting for someone to test that, Mubiin would do it if he had the time but I guess he's bussy right now.
> 
> The issue is probably cause by gambas2 versions incompatibility which the latest script should have solved, apparently it doesn't OR the source code is not incompatibility with the versions Ubuntu provides for you.

Some useful information:
- host is Ubuntu 12.04 64-bit
- Gambas2 v2.23.1
- last 4 comments on issue #19 are relevant for this one

Feedback from other users and patches welcome.

**Comment by bp0** [comment]
I have the same problem with the same versions.
I used the gambas3 ppa:

add-apt-repository ppa:nemh/gambas3
apt-get update
apt-get install gambas3-dev gambas3-gb-*
./install.sh -b gambas3 -i

**Comment by fluxer** [comment]
Oh, geez! if one tee-ed the output of the script and provided it with the bug report it would be easier. 

Anyway, here is the fixed script for installation: http://pastebin.com/u51RK2r3
