### ISSUE TITLE
Install.sh fails for gambas3 branch on Ubuntu 12.10 32bit

### ISSUE THREAD

**Issue by ya55en** [clearkimura/Customizer#22]
On Ubuntu Desktop 12.10 i386, following the User Guide for installing the gambas3 branch, I do this:

(1) download the install.sh from https://github.com/downloads/fluxer/Customizer/install.sh
(2) issue 'sudo ./install.sh -b gambas3 -i'   ## note that the Gide erroneously ommits the -i !)
Here's what I get:

E: Unable to locate package gambas2-gb-gtk
E: Unable to locate package gambas2-gb-form
E: Unable to locate package gambas2-runtime
E: Unable to locate package gambas2-devel
[ERROR] Unable to install the dependencies

After fixing the internals to refer to gambas3-\* packages, and the 'gambas3-devel' to be 'gambas3-dev', I still get errors during installation:
- gbr3: PASSED
- gbc3: PASSED
- gba3: PASSED
  # Cloning from Git
- Branch: gambas3
- URL: git://github.com/fluxer/Customizer.git
- Directory: /opt/Customizer
  Cloning into '/opt/Customizer'...
  remote: Counting objects: 286, done.
  remote: Compressing objects: 100% (210/210), done.
  remote: Total 286 (delta 181), reused 133 (delta 74)
  Receiving objects: 100% (286/286), 322.18 KiB | 341 KiB/s, done.
  Resolving deltas: 100% (181/181), done.
  # Compiling and archiving binary
- Compiling
  gbc: error: Component not found: &1 gb.image
  [ERROR] Unable to compile binary

Really Frustrating. How can one install the gambas3 branch on Ubu 12.10?

**Comment by thiagojedi** [comment]
the "-b gambas3" shouldn't try to locate gambas2 libs... I'll check the dependencies again for 12.10

**Comment by fluxer** [comment]
Use that: http://pastebin.com/axTXDGBm

**Comment by axlroden** [comment]
this still happens for me.. ubuntu 13.04

**Comment by fluxer** [comment]
Try https://gist.github.com/fluxer/5892774 and report back.

**Comment by axlroden** [comment]
I get same output:

sudo ./install.sh -i -b gambas3

and at the end:
Reading state information... Done
E: Unable to locate package gambas2-gb-gtk
E: Unable to locate package gambas2-gb-form
E: Unable to locate package gambas2-gb-image
E: Unable to locate package gambas2-runtime
E: Unable to locate package gambas2-dev
[ERROR] Unable to install the dependencies

seems like the existing dependencies gets set after _check_branch

**Comment by fluxer** [comment]
You need to pass "-b gambas3" before "-i":
sudo ./install.sh -b gambas3 -i

**Comment by axlroden** [comment]
yea I just realized that would work, its the way you parse the arguments.

**Comment by fluxer** [comment]
Yep, I adjusted that just now. The order in which you pass the arguments doesn't matter now.

**Comment by axlroden** [comment]
yep works both ways now.

**Comment by fluxer** [comment]
The new install script will be uploaded and the link to it in the user-guide updated shortly.
