### ISSUE TITLE
insserv doesn't work with dpkg correctly in mini remix

### ISSUE THREAD

**Issue by confido117** [clearkimura/Customizer#23]
I'm trying to use Ubuntu Mini Remix as a base for a very specialized derivative, but when trying to install/remove packages inside the chroot, insserv complains about nonexistent files or directories, and dpkg finishes with errors. One of the more important packages that runs into this issue is wpasupplicant, which is needed by wicd-daemon (a wireless manager daemon), and it can never install. Would this be in the remix itself, is it something about Customizer, or am I just a silly knucklehead?

**Comment by fluxer** [comment]
More info will be required. Would you mind providing more information about the release of UMR and the output of dpkg/apt when you try to install/remove packages, as a start?

**Comment by confido117** [comment]
Erm. Nevermind, I just discovered that it has to do with dangling symlinks and not finding them correctly. Wonder if it'd be safe to leave dangling symlinks.......?
