### ISSUE TITLE
vmlinuz.efi not found after build with 12.04-2 x64

### ISSUE THREAD

**Issue by sylviette** [clearkimura/Customizer#24]
Hello,

after having built my ISO from an Ubuntu 12.04-2 x64 ISO, at boot it gives me /casper/vmlinuz.efi not found. I've spent a little time looking into /opt/Customizer/scripts/rebuild but I haven't found a way to correct it. 
For the moment, being in a rush, I've just copied /casper/vmlinuz into /casper/vmlinuz.efi in ISO directory but that's not a solution, obviously, just a bad patch due to my being late with job.

Thanks,
Silvia

**Comment by fluxer** [comment]
Fixed in all three branches.
