### ISSUE TITLE
/etc/lsb-release issue when changing username/hostname in Ubuntu

### ISSUE THREAD

**Issue by sylviette** [clearkimura/Customizer#25]
Hi,

I've verified it on edubuntu precise and quantal, never noticed on 10.04, anyway. It happens that if I modify hostname and username (via shell and /etc/casper.conf), then in brand new live dvd /etc/lsb-release becomes (that's quantal's case; for precise is the same, mutatis mutandis):

DISTRIB_ID="Ubuntu"
DISTRIB_RELEASE="12.10"
DISTRIB_CODENAME=quantal
DISTRIB_DESCRIPTION="Ubuntu 12.10"

with double-quotes in 1st and 2 nd line.
That causes a crash in Software Center ("no such distribution: ubuntu" or something similar after python errors): if I modify /etc/lsb-release purging from it double quotes, then SC works without problems.

I've noticed it for the first time on precise, due to apport's notice (one of our users told me about that for the first time); apport is bullsh**\* and normally I purge it before creating the ISO and SC is pretty useless, but questioning about that with a guy in Ubuntu-it forum, he checked his /etc/lsb-release and we noticed he hadn't double quotes (he didn't change username and/or hostname, anyway).

Don't know exactly if is a Customizer issue but with UCK (less powerful than Customizer) it doesn't happen.

Thanx,
Silvia

**Comment by fluxer** [comment]
1. What do you mean with "via shell"? Are you editing /etc/casper.conf from a chroot terminal with nano/vim/whatever?
2. From which branch did you installed Customizer? Master, gambas3, devel?
3. If the answer to 1 is no, then are you inserting quotes into the text-field yourself? There is no need for that.

Also, if you are using the GUI then start customizer from terminal, extract unmodified ISO and watch the output in the terminal for Get_Str(), Replace_Str() and Replace_Str_AsIs messages which print enough information and if there is a problem with the quotes you can find out what's going on. I will do this myself but not tomorrow (It's my birth-day :p), and probably not the day after tomorrow.

Cheers!

**Comment by sylviette** [comment]
![screenshot](https://f.cloud.github.com/assets/4247175/453051/d32f31ac-b305-11e2-8466-dc9b488d3b9d.png)
Hello!

1) it means I've modified it using vi from chroot environment but I'haven't inserted any quote by myself ... I swear! :-)
2) from gambas3
3) I didn't.

More clearly ... this evening I did a test on my home pc: I've loaded into Customizer a brand new image from edubuntu's dl page, then I've changed username/hostname from ubuntu/ubuntu to anassa/afrodite (btw ... anassa means "queen" in ancient greek ;-) ) directly into Customizer main interface, i.e. without touching casper.conf. In chroot shell, that's what Ive found out for lsb-release (notice double quotes in release field, NOT inserted by myself but from myself removed):

(chroot)root@saffo:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE="12.04"
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04"

and that''s what Ive found out for casper.conf [here I write (commented) instead of classical hash because of this page formatting problems]:

(chroot)root@saffo:/# cat /etc/casper.conf 
(commented) This file should go in /etc/casper.conf
(commented) Supported variables are:
(commented) USERNAME, USERFULLNAME, HOST, BUILD_SYSTEM, FLAVOUR

export USERNAME="anassa"
export USERFULLNAME="Live session user"
export HOST="afrodite"
export BUILD_SYSTEM="Ubuntu"

(commented) USERNAME and HOSTNAME as specified above won't be honoured and will be set to
(commented) flavour string acquired at boot time, unless you set FLAVOUR to any
(commented) non-empty string.

(commented) export FLAVOUR="Ubuntu"

Notice that last line was still commented, this way at boot username/hostname would be ubuntu/ubuntu, accordingly to what is written in casper.conf

Finally I did some fine tuning from chroot WITHOUT changing lsb-release, then both before generating the image and after having generated the iso and mounted it on a vm , I took a look to lsb-release, finding what follows:

(chroot)root@saffo:/# cat /etc/lsb-release 
DISTRIB_ID="Ubuntu"
DISTRIB_RELEASE="12.04"
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04"

(after having generated the iso, obviously, instead of (chroot)root@saffo:/# cat /etc/lsb-release I got anassa@afrodite:~$ but for lsb-release the same thing with double quotes).

That's all.

And finally, happy birthday! (it was my husband's birthday too, today ... funny, huh?)

Silvia

**Comment by fluxer** [comment]
FLAVOUR is something new to me, perhaps it's introduced in 12.04 and later? I Believe that the issue has been addressed, it would be nice if you can test and report back. Just re-install Customizer with the script (or manually, if you prefer so) but keep in mind that the fix is currently only in the gambas3 branch. If all works good I will push the fix to master too.

And thanks for the cheers!

**Comment by fluxer** [comment]
Just tested it, DISTRIB_ID and DISTRIB_RELEASE are handled properly now and the values are not quoted. Pushing to master.
