### ISSUE TITLE
Unable to chroot and get the architecture

### ISSUE THREAD

**Issue by tienvx** [clearkimura/Customizer#26]
I download Customizer from https://github.com/clearkimura/Customizer version 3.2.2
Extract it to /opt
Rename Customizer-3.2.2 to Customizer
Run this command: sudo /opt/Customizer/GUI.gambas
Change working directory to /media/Disk/Temp
This error occurs:

[*] Checking architecture
chroot: failed to run command `dpkg': Permission denied
[X] Unable to chroot and get the architecture

I'm using ubuntu 12.04 64bit

**Comment by fluxer** [comment]
Grab a master checkout either via Git or from https://github.com/clearkimura/Customizer/archive/master.tar.gz.
