### ISSUE TITLE
/tmp

### ISSUE THREAD

**Issue by kerroncheddie** [clearkimura/Customizer#3]
file/folder permissions needs to be set
mkdir /tmp  seems to mess up the usage of the folder
but  chmod 1777 /tmp seems to fix the issue.

hope this helps.

**Comment by fluxer** [comment]
Fixed in master and devel branch. Now the files inside /tmp will be deleted instead of the directory so permissions will remain as they were:

rm -rf /tmp/\* /tmp/.??*
