### ISSUE TITLE
Ubuntu 12.04 host, Customizer 3.2.3, ubuntu-mini-remix-13.04-i386. Using Remix ISO,', cannot init live session , Terminal shows autentiphacion  

### ISSUE THREAD

**Issue by mitsuzero** [clearkimura/Customizer#30]
i cant boot in the remix how i created with this tool. 
Ubuntu:12.04
user autenticacion failure
im not passing to desktop or install.
can you help me, please?

**Comment by fluxer** [comment]
1. Extract an ISO, chroot (not with Customizer) into $WORK_DIR/FileSystem and cat /etc/casper.conf and /etc/lsb-release.
2. Rebuild the ISO, chroot (not with Customizer) into $WORK_DIR/FileSystem and cat /etc/casper.conf and /etc/lsb-release.
3. Paste the output here, via gist, pastebin or whatever suits you.

**Comment by mitsuzero** [comment]
http://pastebin.com/ZEy6LgFB this is for the output for lsb_release and casper.conf

**Comment by fluxer** [comment]
You've done some changes I see, I need the stock files content and those after the rebuild, you did only step 2 and you did it with the GUI (with Customizer) where I told you not to.

**Comment by mitsuzero** [comment]
I didnt understand ... how i do it...

**Comment by ghost** [comment]
@mitsuzero 
Basically, @fluxer wants you to do manual chroot and see if the rebuilded ISO using manual chroot is same with case of using Customizer. If you are new to chroot, there is a short documentation on Ubuntu Community site:
https://help.ubuntu.com/community/BasicChroot

If you still don't know how to do chroot, let's try other way: rebuild the 13.04 source ISO without making changes i.e. don't change username, hostname, etc:
1. Click 'Select ISO' to extract and
2. Click 'Rebuild ISO' to create new ISO.
3. Try boot the created ISO can be boot as Live CD on host machine or virtual machine.

And feedback to us the result.

**Comment by mitsuzero** [comment]
i see in the "terminal"  some error when start live cd .. the command
Adbuser (or some text) command not found.... i think this can cause the
problem... but wait some time... to do it...

2013/9/9 clearkimura notifications@github.com

**Comment by ghost** [comment]
@mitsuzero 
When you have time to do this, kindly send us some screenshots of error you had seen.
Pictures would be useful to understand better.

Until then, I will mark this issue as "Unknown".

**Comment by ghost** [comment]
@mitsuzero 
This issue has been opened for a month by now, and so far no feedback yet. So I will be closing this issue for now.
But if you really have time to work on this issue again, feel free to reopen this issue.

**Comment by mitsuzero** [comment]
Sry about not reply in time. im use a "workaround" ... im create the user in the process(in the chroot) .. the error is showing but i can login... :+1:   but in this time i check into /etc/udev/  for the error... if i find a solution i post here... :)
