### ISSUE TITLE
Ubuntu 13.04 unmet dependencies

### ISSUE THREAD

**Issue by brylie** [clearkimura/Customizer#31]
E: Unable to locate package gambas2-gb-gtk
E: Unable to locate package gambas2-gb-form
E: Unable to locate package gambas2-gb-image
E: Unable to locate package gambas2-runtime
E: Unable to locate package gambas2-dev
[ERROR] Unable to install the dependencies

I do have access to the package 'gambas3' ... etc. Can the installer script be updated to accept gambas3-*

**Comment by fluxer** [comment]
Read the documentation, for Ubuntu 12.04 and later releases you must install from the gambas3 branch.

**Comment by brylie** [comment]
On 21.09.2013 11:50, Ivailo Monev wrote:

> Read the documentation, for Ubuntu 12.04 and later releases you must
> install from the gambas3 branch.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/clearkimura/Customizer/issues/31#issuecomment-24858740.
> 
> Also, is there any documentation describing how to install the gambas3
> branch? It would be helpful to include dependencies and necessary
> commands to get Customizer up and running.

Thanks! :-)
--Brylie Oxley

**Comment by fluxer** [comment]
https://docs.google.com/document/d/1PfhHnSBjv-IDI7Yh5obhMGYCAV9Gw1NPEynU4GqKTsA

**Comment by ghost** [comment]
@brylie 
Your feedback on "documentation is hard to find" is well understood. Even we had kept the documentations updated, but I do admit that contents are not centralized. We'll try to improve this gradually. Thanks for your honest feedback!

@fluxer 
I'll try to unify all resources and present via GitHub only. Major clean up is on the way..
