### ISSUE TITLE
myslq doesn't start after installing in customizer

### ISSUE THREAD

**Issue by jmelton98** [clearkimura/Customizer#32]
Using the "Terminal" in Customizer, I installed mysql, but it does not run. I have tried "service mysql start" and nothing happens as well as "netstat -tap | grep mysql" and nothing shows up. I need to get mysql to run inside Customizer in order to finish my ubuntu remix. Am I missing something? Is there a way to get mysql to run in Customizer terminal window?

Thanks,
Jon

**Comment by jmelton98** [comment]
The same appears to be true for nginx. Nothing shows up for nginx after starting nginx and running "netstat -tap | grep http".

**Comment by ghost** [comment]
Firstly, you have not mentioned the details of your environments setup (
host system, ISO image versions, et cetera ) and any log files of error you
mentioned above.

Hence, this issue is more like "how to install and run MySQL and nginx in
chroot environment", rather than issue with Customizer itself.

Have you try to setup these correctly as advised on the web? Some links are
included below.

http://www.symantec.com/connect/articles/securing-mysql-step-step
http://stackoverflow.com/questions/5056710/running-mysql-in-chroot
http://www.cyberciti.biz/faq/howto-run-nginx-in-a-chroot-jail/

Unless you can show that MySQL and nginx can run in manually prepared
chroot environment, but _not_ able to do so in Customizer, this issue will
be treated as "Invalid".

Kindly provide details and result of above setup.

**Comment by ghost** [comment]
Until the next reply comes, I will mark this issue as "Unknown".

**Comment by jmelton98** [comment]
First let me start off with the fact that I love Customizer! It is easy to use and has allowed a noob like me to create my own custom remix, which quit an accomplishment. I thank you for creating such an amazing tool!

Now on to my issue, which is not a bug in Customizer ;P . 

Yes, I agree with your assessment that this issue is with chroot and not Customizer, I just didn't know where to start. So with this new information in hand I have been googling for a solution and trying different things, and nothing seems to work. I know that this it probably not the best place for this, but since there does not appear to be a forum for Customizer, I am hoping I can ask for some additional direction on how to proceed.

My problem is that I need to temporarily get MySQL to run properly in Customizer (chroot) so that I can install some software which has MySQL dependencies. After I get the software installed, I need to then return MySQL to its normal state of operation (non chroot) so that it installs properly from the LiveCD. Is this something that can be (easily) done in Customizer? Is there a workaround or a hack I can use to achieve this?

Sorry for posting this here, I am just stuck and unfortunately can't move forward with my Ubuntu remix until I can get this resolved. 

Thank you for your valuable time!

Host System: Elementry OS
ISO Image: Ubuntu 13.04 desktop 64bit

**Comment by ghost** [comment]
@jmelton98 
The developer of Customizer is @fluxer , so the first credit should be given to him. I am mainly helping out with documentation and sometimes testing on host system and ISO images. If you had written a review on Customizer, share us the link and we will cite on GitHub wiki.

And back to your issue, have you tried the links I had given to you above i.e. on how to install and setup MySQL on Ubuntu? I have several more suggestions for you to try:

https://help.ubuntu.com/lts/serverguide/mysql.html
http://hendrelouw73.wordpress.com/2013/04/20/how-to-install-mysql-5-5-on-ubuntu-12-04-linux/

In both sources, you are required to create a root account before you can actually run MySQL services. Most of the sources cites that user will be asked to create root account during installation. Did you create one?

If that doesn't work either, I would suggest you to ask on IRC or community sites ( like askubuntu or elementaryos.org ). You can search "how to install and run MySQL in chroot on Ubuntu/elementaryOS?" on these sites first. If no such question exists, create one there.

This is as far as I could help.

Anyway, I will mark as "Invalid" and close this issue.
