### ISSUE TITLE
Desktop items not showing up in Xyphyr but do show in final build

### ISSUE THREAD

**Issue by Rdrit** [clearkimura/Customizer#33]
I had removed some previously used files and folders from using Xyphyr however after building they continue to show up on the desktop of the built version. If I go back to Xyphyr they are gone.

**Comment by ghost** [comment]
@Rdrit 
First of all, this is not an issue or bug. Just a little misunderstanding of remastering process.

Whenever using Xephyr, all changes will be made to `/home/FileSystem/root` (your home directory while chroot). However, after exiting Xephyr, those changes will be copied from there to `/home/FileSystem/etc/skel` (the "default" home directory of Live CD after rebuild).

So to revert any changes made in Xephyr, you must remove the previously used files and folders from both directories above.

In your case, you didn't remove those files from latter directory yet.
- In Customizer GUI, go to menubar, click on **Directories** > **/home/FileSystem/etc/skel**
- A **File Manager** will be launched with selected target path
- Double-click **Desktop** folder icon
- Delete your previously used files and folders in this directory

And that's it. Do these solve your issue?

**Comment by Rdrit** [comment]
Yes it did..Thank you very much!

**Comment by ghost** [comment]
@Rdrit 
Glad to hear your feedback!
Problem solved, so I'm closing this issue.
