### ISSUE TITLE
QEMU resolution

### ISSUE THREAD

**Issue by sylviette** [clearkimura/Customizer#39]
Hi,
I don't know if it's a real issue or just my fault ;-) but if I try to run the customized filesystem from QEMU, using a Ubuntu 12.04 custom fs, it emulates it in a 1024x768 screen while if I'm using a 13.04 or 13.10, it emulates it in a much larger screen, not accessible in any of its parts.
I took a look to qemu in /opt/Customizer/script, but screen resolution wasn't there.

Thanks,
Silvia

**Comment by fluxer** [comment]
The RESOLUTION option controls only the Xephyr (nested X-session) window resolution. Is it possible to specify QEMU window resolution at runtime?

**Comment by fluxer** [comment]
As far as I can tell there is not argument for controlling the QEMU window size (see http://wiki.qemu.org/download/qemu-doc.html#sec_005finvocation), thus marking as invalid. It's not Customizer that decides what the size of the QEMU window will/should be.

**Comment by sylviette** [comment]
Thanks, Ivailo. It isn't a so critical problem, anyway.

My best wishes for incoming holidays,

Silvia

---

τὸν δ' αἰσχρῶς ἐνένιπε Μελανθὼ καλλιπάρῃος,
τὴν Δολίος μὲν ἔτικτε, κόμισσε δὲ Πηνελόπεια,
παῖδα δὲ ὣς ἀτίταλλε, δίδου δ' ἄρ' ἀθύρματα θυμῷ·

Hom. Od. xviii 322-24

Date: Sat, 21 Dec 2013 05:19:31 -0800

**Comment by fluxer** [comment]
Happy holidays to you too, Silvia!
