### ISSUE TITLE
sytntax error!

### ISSUE THREAD

**Issue by mbnoimi** [clearkimura/Customizer#46]
Unable to compile the binary because of:

```
mbnoimi@mbnoimi-pc ~ $ wget https://dl.dropboxusercontent.com/u/54183088/install.sh && chmod +x install.sh && sudo ./install.sh -b gambas3 -i
--2014-01-19 18:29:55--  https://dl.dropboxusercontent.com/u/54183088/install.sh
Resolving dl.dropboxusercontent.com (dl.dropboxusercontent.com)... 54.225.194.197
Connecting to dl.dropboxusercontent.com (dl.dropboxusercontent.com)|54.225.194.197|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7805 (7.6K) [text/x-sh]
Saving to: ‘install.sh’

100%[======================================>] 7,805       --.-K/s   in 0s      

2014-01-19 18:30:01 (1.97 GB/s) - ‘install.sh’ saved [7805/7805]

[sudo] password for mbnoimi: 
# Checking dependencies
   * git: PASSED
   * mktemp: PASSED
   * rsync: PASSED
   * tar: PASSED
   * xhost: PASSED
   * Xephyr: PASSED
   * convert: PASSED
   * dbus-daemon: PASSED
   * mksquashfs: PASSED
   * unsquashfs: PASSED
   * genisoimage: PASSED
   * qemu-system-x86_64: PASSED
   * gbr3: PASSED
   * gbc3: PASSED
   * gba3: PASSED
# Purging old version: /opt/Customizer
# Cloning from Git
   * Branch: gambas3
   * URL: git://github.com/fluxer/Customizer.git
   * Directory: /opt/Customizer
Cloning into '/opt/Customizer'...
remote: Counting objects: 48, done.
remote: Compressing objects: 100% (45/45), done.
Receiving objects: 100% (48/48), 109.75 KiB | 46.00 KiB/s, done.
Resolving deltas: 100% (8/8), done.
remote: Total 48 (delta 8), reused 25 (delta 1)
Checking connectivity... done
# Compiling and archiving binary
   * Compiling
FMain.class:149:2: error: Syntax error
[ERROR] Unable to compile binary
mbnoimi@mbnoimi-pc ~ $ 
```

**Comment by ghost** [comment]
@fluxer 
Based on error shown by @mbnoimi above, it seems that `FMain.class` file has syntax error.

The only difference between latest file and previously updated file (nine months ago) is the recent patch applied to solve issue #45. The additional codes in line 149, 150 and 158, 159 seemed to have incompatible syntax with gambas3 branch.

This issue has no effect on master branch, as we have tested recently.

**Comment by mbnoimi** [comment]
@clearkimura 

> This issue has no effect on master branch, as we have tested recently.

But as I read from install.sh it seems that git://github.com/fluxer/Customizer.git is the used repository so I suppose the master branch will fail to build

**Comment by fluxer** [comment]
You didn't read the output carefully, the Git url is the same - the branch is not!

In any case, something has changed with gambas3 syntax or I messed up badly. I will look into it

**Comment by mbnoimi** [comment]
After updating the new Gambas everything went well

**Comment by fluxer** [comment]
@mbnoimi Can you tell us which version did you used before the update so (possibly) @clearkimura can document this in the user guide?

**Comment by mbnoimi** [comment]
@fluxer 
Gambas 3.1.1-2 under Linux Mint x64 Cinnamon

**Comment by ghost** [comment]
@mbnoimi 
@fluxer 
Noted from both of you. User guide has been updated under "2.1 System requirements".

I didn't face this issue because I am using Gambas3 PPA, which pulls out latest stable version 3.5.2-2precise1 on Xubuntu 12.04.

Changed label from "pending" to "invalid" because no fixes needed for Customizer.
