### ISSUE TITLE
Customize distro desktop for custom locale

### ISSUE THREAD

**Issue by zxuser** [clearkimura/Customizer#5]
Can I run Desktop Environment via Customizer with other then "en_US.UTF-8" locale?

I have problem:
1. I change some Firefox settings (install add-on) via Desktop Environment in Customizer and than create disk image.
2. Install Custom Ubuntu (use disk image file) and choose "ru_RU.UTF-8" locale.
3. After installation i have localized Desktop Environment (GNOME), but Firefox browser is not localized (for example, MenuBar hava File, Open, etc... instead of Файл, Открыть)

**Comment by fluxer** [comment]
Hello!

You should be able to, you just need to setup the locales in the filesystem you are customizing. 

As far as for the issue after installation maybe there are bad/missing translations or something else. Can you confirm that the problems is only with the customized the image and not present in the regular K/X/L/Ubuntu release? And which one distribution and release are you refering to?

**Comment by zxuser** [comment]
I customize Ubuntu 11.10.
I try to set up locales in Terminal (in Customizer) with commands:
locale-gen "ru_RU.UTF-8"
update-locale LANG="ru_RU.UTF-8" LANGUAGE="ru_RU.UTF-8" LC_ALL="ru_RU.UTF-8"
To check locale changes i look in /etc/default/locale
cat /etc/default/locale 
#  File generated by update-locale
LANGUAGE=ru_RU.UTF-8
LANG=ru_RU.UTF-8
LC_ALL=ru_RU.UTF-8
But it's not enough to change locale.
In Terminal (In Customizer) i use commands:
export LANG="ru_RU.UTF-8" 
export LANGUAGE="ru_RU.UTF-8"
export LC_ALL="ru_RU.UTF-8"
After that terminal messages are localized:
for example, "apt-get update" output.

But in Desktop (in Customizer) i can't export locale settings before GNOME session start.

Yes, this localization problem only with the customized image.

My OS is Linux Mint 11 (Katya) based on Ubuntu 11.04.
Customizer version 3.2.2.

update:
I try to change locale in GNOME session. But it failed.
When I click "Language support" in System Settings there are only messages in Terminal (which appears with Xephyr window):

Traceback (most recent call last):
  File "/usr/bin/gnome-language-selector", line 27, in <module>
    options=options)
  File "/usr/lib/python2.7/dist-packages/LanguageSelector/gtk/GtkLanguageSelector.py", line 172, in **init**
    self.ac = aptdaemon.client.AptClient()
  File "/usr/lib/python2.7/dist-packages/aptdaemon/client.py", line 1046, in **init**
    self.bus = dbus.SystemBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 202, in __new__
    private=private)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 108, in __new__
    bus = BusConnection.**new**(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 125, in **new**
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

**Comment by fluxer** [comment]
I will have to check if these are the correct steps to setup the locales in Ubuntu/Linux Mint as I'm not running Ubuntu for some time and I didn't messed that much with the locales.

In the meantime I can give you a temporary solution for the locales setup before launching the DE with Customizer. It requires from you to edit the xnest script (/opt/Customizer/scripts/xnest) as root and change this:

**chroot** "apt-get install dbus -y -f
export DISPLAY=localhost:9
dbus-uuidgen --ensure;
$EXEC_COMMAND"

to look like this:

**chroot** "export LANGUAGE=ru_RU.UTF-8
export LANG=ru_RU.UTF-8
export LC_ALL=ru_RU.UTF-8
apt-get install dbus -y -f
export DISPLAY=localhost:9
dbus-uuidgen --ensure;
$EXEC_COMMAND"

This should do for you until the next release of Customizer (won't be soon). If you have the skills you can fork the project and add an option or something to setup locales at chroot, I will push them to the stable branch. The base of Customizer is just Bash scripts soe it won't be that hard. If you need help with that you can email me (see my profile page).

**Comment by zxuser** [comment]
Thanks a lot for the helpful information. It's solved my problem.
I've got some bash scripting skills and I try to add such option in fork.
I'll contact you.

**Comment by fluxer** [comment]
On the update: "/var/run/dbus/system_bus_socket: No such file or directory", this is the important part. Now, Customizers mounts (binds) /var/run/dbus and /var/lib/dbus to the filesystem you are chrooted into however I've noticed some quirks, it is known and is noted in the google docs manual (https://docs.google.com/document/d/1PfhHnSBjv-IDI7Yh5obhMGYCAV9Gw1NPEynU4GqKTsA/edit, issue 4.1.6).

To have a proper dbus setup in the chroot binding those directories and running "dbus --ensure" should work but sometimes it doesn't. The only thing I can think right now is to try to "touch" the missing file so even tough it doesn't have a proper content it is there and pray that applications relying on dbus will work.

I've never managed to overcome some issues with the nested X-sessions but I will gladly appreciate patches.

**Comment by ghost** [comment]
Good day,

I'll answer with respect to no.3.

To localize Firefox, it requires language pack to be installed
separately. Firefox will _not_ be affected by locale file provided by
Desktop Environment.

You can find your language pack at Mozilla Addon homepage, URL as below.
 https://addons.mozilla.org/en-US/firefox/language-tools

Hope I have answered your question.

On 10 April 2012 22:49, zxuser
reply@reply.github.com
wrote:

> Can I run Desktop Environment via Customizer with other then "en_US.UTF-8" locale?
> 
> I have problem:
> 1. I change some Firefox settings via Desktop Environment and than create disk image.
> 2. Install Custom Ubuntu (use disk image)  file and choose "ru_RU.UTF-8" locale.
> 3. After installation i have localized Desktop Environment (GNOME), but Firefox browser is not localized (for example, MenuBar hava File, Open, etc... instead of Файл, Открыть)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fluxer/Customizer/issues/5

## 

MUBIIN
clearkimura@gmail.com

**Comment by fluxer** [comment]
There are also locale packages in the Ubuntu repositories: http://packages.ubuntu.com/search?keywords=firefox&searchon=names&suite=oneiric&section=all

**Comment by zxuser** [comment]
Thank you for your interest!
But there is other kind of problem.

As I understand:

During installation Ubuntu automatically download required languages pack, translation, etc based on previously chosen language.
So, Firefox language pack for Russian language installed in customized system after installation.

I create Firefox settings (via launching Firefox, installing add-ons) in DE with Customizer. And this settings (according to my hypothesis) hold Firefox locale value based on DE locale.

In practice, after installation customized Ubuntu (I choose Russian language during installation) I get such results:
If DE with Customizer had "en_US" locale, I'll get English language version Firefox in Russian language DE.
If DE with Customizer had "ru_RU" locale, I'll get Russian language version Firefox in Russian language DE.

So, changing locale of DE with Customizer solves the problem.

**Comment by fluxer** [comment]
Ok, closing issue. If you feel the need for further discussion send me an email to reopen it.
