### ISSUE TITLE
ISSUE-2011-003 (GUI with unexpected error at startup)

### ISSUE THREAD

**Issue by ghost** [clearkimura/Customizer#53]
The GUI acts strange or exits with unexpected error during startup
##### Environment

Unknown
##### Description

The GUI is written in Gambas2 version 2.24 and the executable file is compiled with it. If you have newer or older version of Gambas this may cause issues.
##### Workaround

None
##### Solution

Install Gambas2 IDE and some additional components:

```
 gambas2-ide gambas2-runtime gambas2-gb-form gambas2-gb-gui
```

Above are the names of Gambas2 packages in Debian/Ubuntu. The names might be different if you are running other OS so use extended search or something when you query it using your package manager!

If the OS don't have package manager or these packages are not in packages database then you will have to compile Gambas. More instructions at  http://gambasdoc.org/help/install

Then, you have the Gambas2 IDE to do the following:
1. If you had installed Customizer with the install script the GUI source should be already in  `/opt/Customizer`, else clone the git with the install script
2. Run Gambas IDE, navigate to `/opt/Customizer/GUI` and click **Open** or double click on the folder, either way will do
3. There is a menu in the top left corner. Navigate to  **Project** > **Clean up** . Now click on  **Tools** > **Update all forms**
4. Navigate trough the same menu **Project** > **Make** > **Executable** and place the executable file in **/opt/Customizer** or replace if needed. If you can't write to that directory then `chmod` it, so you can!

Last updated: 2014-02-08

**Comment by ghost** [comment]
This issue only affects existing master branch (GUI built on gambas2). Although, I never face this issue since I started using Customizer version 3.0.5 until now.

The gambas3 and devel branches are presumably unaffected by this issue.

**Comment by fluxer** [comment]
I have, transfering the binary from one distribution (Ubuntu) to another (Debian)
which ship slitely different versions of Gambas2 can trigger the issue, that is
how I found it. But since the Gambas2 branch does not have much use anymore
I'm closing this.
