### ISSUE TITLE
ISSUE-2011-005 (Filesystem is locked)

### ISSUE THREAD

**Issue by ghost** [clearkimura/Customizer#55]
Filesystem is locked permanently
##### Environment

Customizer 3.1 and newer releases, regardless of the environment.
##### Description

When chrooted Terminal is launched then closed using window manager i.e. ‘Close button’, rest of customization options (such as **Archive**, **Install DEB**, **Desktop**, **Extras** > **Install GUI**) becomes unusable.

When clicked on one of these options, the Terminal prompt always show the error message below.

```
...
[x] The filesystem is locked
```
##### Workaround

Use either one of methods below on your host system.

Graphical method
- Open a File Manager as root
- Navigate to `/home/FileSystem/tmp` directory
- Delete `lock_chroot` and `script.sh` files

Command-line method
- Open a Terminal
- Type `sudo rm -rf /home/FileSystem/tmp/*` and hit **Return** key
##### Solution

Always type `exit` and hit **Return** key to close the chrooted Terminal.

Since Customizer 3.1.1, a warning message has been added in the chroot Terminal. If the user still attempts to close with window manager, this issue can be reproduced.

Last updated: 2014-02-08

**Comment by fluxer** [comment]
No longer relevant, development has moved on.
