### ISSUE TITLE
ISSUE-2011-006 (Keyboard mapping doesn't work in Xephyr)

### ISSUE THREAD

**Issue by ghost** [clearkimura/Customizer#56]
When Desktop is launched, the keyboard mapping doesn’t work as it should even keyboard has been grabbed with  Ctrl + Shift  key combination.
##### Environment

Customizer 3.2 and newer releases, regardless of the environment.
##### Description

The Desktop refers to X-nested session in Xephyr. The alphanumeric keys, **space bar**, **Backspace** works; but  ↑  key is mapped to  PrntScrn,  →  key is mapped to **Alt**, and **Delete** keys, etc. doesn't work or mapped to unknown keys.
##### Workaround

Use mouse clicks and selections to do most of things. Instead of **Delete** key, use mouse cursor to select and **Backspace** key to delete particular words.
##### Solution

Upgrade Xephyr to latest version. Else, use backports for Ubuntu/Debian if needed (untested).

Last updated: 2014-02-08

**Comment by fluxer** [comment]
You should let the Ubuntu packagers of Xephyr (Xorg) about this so this can be fixed on their side.

**Comment by ghost** [comment]
@fluxer 
Someone had reported [this bug in 2010](https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/585564) and user stopped sending feedback in 2011. Just several days ago, Launchpad Janitor had closed the issue for long inactivity.

If I recall correctly, I have at least face this issue on 10.04 with GNOME 2.30. Not sure if I have also faced on 12.04 with XFCE that time (although I did wrote "regardless of the environment" in this issue post).

This issue needs further clarification before going for second-time bug report.

So.. earlier today, I checked again by running Customizer on Xubuntu 12.04 inside VirtualBox 4.3.4 emulator. Loaded with Ubuntu Mini Remix 12.04 with minimal XFCE 4.8 environment.

The "Desktop" feature (Xephyr) works without problem. No problem with the key mappings. The **Delete**, **↑** and **→** keys works as it should. Yes, it works normally on 12.04 (at least virtually emulated keyboard in VirtualBox does).

Huh, why works now? Not sure. I didn't update Customizer or its dependency packages. Just continue from where I had left many months ago. Perhaps I have been ignorant for testing on physical machine (not to mention a retired machine, now disposed via a trade-in program).

Hence updated with the following comment after this.

**Comment by ghost** [comment]
To this date, only Ubuntu 10.04 LTS Lucid Lynx is known to have this issue.

In particular, host system environment is the main cause of this issue (at least GNOME 2.30 host is affected by this). That is why the issue above describes as "regardless of environment" (of the remix).

**Comment by fluxer** [comment]
Lucid is EOF.
