### ISSUE TITLE
ISSUE-2013-001 (Building older release ISO fails to boot)

### ISSUE THREAD

**Issue by ghost** [clearkimura/Customizer#57]
When building remix of older release ISO image on newer release host system, the rebuilded ISO image failed to boot and falls back to BusyBox built-in shell.
##### Environment

Customizer 3.2 and newer releases, regardless of the environment.
##### Description

In actual case, when building remix of 10.04 ISO image on 12.04 host system, the rebuilded ISO image succeed to start as Live CD however, had failed to boot at splash screen and displays the following error:

```
 BusyBox [..] built-in shell (ash)
 Enter help for a list of built-in commands.

 (initramfs) Can not mount /dev/loop0 [..]
 _
```

This issue is likely caused by creating older filesystem using newer version of squashfs-tools. In this case, the user tried to create a filesystem for Ubuntu 10.04 Lucid Lynx release using squashfs-tools in Ubuntu 12.04 Precise Pangolin.

In opposite case, when user tries to create a filesystem for Ubuntu 12.04 Precise Pangolin release using older squashfs-tools on Ubuntu 10.04 Lucid Lynx host system, user did _not_ face this issue at all. Live CD can boot normally--at least tested with mentioned LTS releases. Untested for regular releases.
##### Workaround

None
##### Solution

Rebuild your remix on the host system that has same release version with your ISO image file release version. For example, a remix of 10.04 ISO image should be rebuilded on 10.04 host system.

Last updated: 2014-03-15

**Comment by fluxer** [comment]
Can you provide the output of `sudo lsmod` in such cases just before the rebuild process and after?
Maybe the loop module is not loaded on the host (unlikely), not added in the initramfs/initrd for some reason.

Also, after booting the remix can you provide the output of `ls /dev/loop*` and `modprobe loop && ls /dev/loop*`?

**Comment by ghost** [comment]
@fluxer 
Noted for future testing. Limited time for doing testing nowadays..

**Comment by hreikin** [comment]
@fluxer @clearkimura I can try recreate this after work and will report back my findings

EDIT : change of plans i have a new HD, 1TB :) im gonna re-install today and try to recreate tomorrow after work

**Comment by fluxer** [comment]
@clearkimura @hreikin Ok.

**Comment by hreikin** [comment]
@fluxer my host system is 12.04 - 32-bit i grabbed 10.04 - 32-bit, ran it thru customizer, changed nothing, then ran command sudo lsmod as suggested, here is the pastebin : 

http://pastebin.com/K2FrnaNa

i then rebuilt the ISO and ran the command again : 

http://pastebin.com/cipmqaCR

as we know this fails with the above error when trying to use the liveCD as mentioned by @clearkimura

in the busybox shell i ran the 2 commands as suggested, here is the output : 

(initramfs) ls /dev/loop*
/dev/loop7   /dev/loop5   /dev/loop3   /dev/loop1
/dev/loop6   /dev/loop4   /dev/loop2   /dev/loop0
(initramfs) modprobe loop && ls /dev/loop*
(initramfs)

hope that helps :)

**Comment by fluxer** [comment]
@hreikin I do not see the loop module being loader, which is funny. Not before and note after the rebuild. Can you try to modprobe the loop module before the rebuild? If the initramfs generating scritps use some sort of magic to put only the currently loaded modules and the loop modules is not loaded during the rebuild you will end up without the loop module in the initramfs - thus causing the fail.

Strange enough, the loop device nodes disappear after the loop module is loaded in the initramfs. I really do not know why is that, maybe udev problem or something?

**Comment by hreikin** [comment]
@fluxer i have no idea why i'm just the tester monkey :P i cleaned the directory then started a fresh, loaded the 10.04 ISO and then ran the command "modprobe loop && ls /dev/loop*" here is the pastebin : 

http://pastebin.com/DFgw46Hi

EDIT : i ran just "modprobe loop" and it returned nothing

**Comment by ghost** [comment]
@hreikin 
Thanks for testing to reproduce this issue. Glad that someone volunteers.

@hreikin @fluxer 
Guys, I have updated issue post with additional information (See **Description**, text begin in new paragraph as "In opposite case.. "). But I think @fluxer know this already.

Just to reconfirm that this issue is valid only when rebuilding an older release of ISO on host system of newer release. Not applicable if the other way round.

**Comment by fluxer** [comment]
@hreikin Sorry, but I forgot to write you that you should modprobe the loop module, rebuild the ISO and see if it boots as usual or leaves you in initramfs shell. Can you do that, please?

@clearkimura Thanks for the update.

**Comment by hreikin** [comment]
@fluxer i loaded the ISO, opened a terminal on the host and ran "modprobe loop" and it returned nothing, i then opened a terminal in Customizer and ran "modprobe loop" and it returned this : 

http://pastebin.com/udMJYYDP

i then rebuilt the ISO and ran "modprobe loop" on the host afterwards and it returned nothing again

upon booting, you get the splash screen then the initramfs shell again, running "modprobe loop" returns nothing

**Comment by fluxer** [comment]
I bet if Proot (https://github.com/cedric-vincent/PRoot) is used the problem will be gone. It can fake other kernel version but first Customizer must know which kernel to amulte (looking at /home/FileSystem/lib/modules for the available kernels) but there may be multiple kernels installed or leftovers from old kernels which would be tricky to do. Including the static PRoot binaries is easy, updating them is easy but code that's using it properly is gonna be tricky. A Debian/Ubuntu user familliar with the kernel files may get this right but I'm not gonna do that.

**Comment by ghost** [comment]
I have tried to build 12.04 Precise Pangolin ISO image on 14.04 Trusty Tahr host system, just to check whether I can reproduce this issue or not.

Apparently, it doesn't.

After boot into Live session, I ran `ls /dev/loop*` command and got output like this:

```
/dev/loop0 /dev/loop2 /dev/loop4 /dev/loop6 /dev/loop-control
/dev/loop1 /dev/loop3 /dev/loop5 /dev/loop7
```

Then, I also ran  `modprobe loop && ls /dev/loop*` command and it gave me same output as above.

In short, the 12.04 ISO image can be boot normally without falling back to BusyBox shell. Although, I have only tried with CLI environment.

**Comment by fluxer** [comment]
Have you tried upgrading the kernel? If the issue can not be reproduced on recent releases after kernel upgrade than I'd say the issue has been fixed by the Ubuntu devs.

**Comment by ghost** [comment]
@fluxer 
Just to refresh some details, the 12.04 ISO image is now using kernel linux-generic version 3.2.0-68.81 (latest from precise-updates repo), rebuilded on 14.04 host system on kernel linux-generic version 3.13.0.24.28 (however latest being 3.13.0.35.42**).

However, because 12.04 is a still supported release, it is possible to upgrade kernel to linux-generic-lts-trusty whose version is almost same as **mentioned (just slightly older 0.35.30).

But if I do this, it means rebuilding ISO image with same kernel version as host system, which of course isn't relevant with this issue (as I already clarify in March this year), quoted as below:

> Just to reconfirm that this issue is valid only when rebuilding an older release of ISO on host system of newer release. Not applicable if the other way round. From [comment 37728929](https://github.com/clearkimura/Customizer/issues/57#issuecomment-37728929).

So, did you mean upgrading kernel on the ISO image, or the host? 

P.S.: The comment back then, I'm not sure whether I meant when using older kernel version or, the older squashfs-tools. If it was latter, then it is still worth to try upgrade both systems to same kernel and rebuild using older squashfs-tools in 12.04. Eh.. can't be. It must be rebuilded on newer host system to reproduce this, so using newer squashfs-tools in 14.04.

P.S.S: Sigh, I am confusing myself. Help me to understand.

**Comment by fluxer** [comment]
Usually, this problem appeared when the  kernel on the ISO image is different version from that on the host. So, to possibly trigger the poblem you have to make this happen. Even if you think they are almost the same the chances for something bad can happen are small but there is that possilibty. 

Both different kernel versions (which means different versions of the squashfs module) and different squashfs-tools can triggers the problem the way I see it simply because things change and they are not always 100% backwards compatible.

I think I've told you before but I will say it again, Debian Live build system copies the guest (or ISO) filesystem and chroots into to compress the final squashfs image so that squashfs-tools is the same version used in the guest filesystem. Now, this can not fully solve the kernel module problem as it can not be loaded from the chroot (AFAIK) but at least ensures some compatibility. Also, it allows them to temporary install and remove packages which remove some of the dependencies required on the host (squashfs-tools and grub to mention a few). This is the safe approach of building/rebuilding ISO but I consider it requires more time and resources especially hard-drive space, imagine if you have to copy a 4.7GB folder and then delete it - the hard-drive space requirement for rebuilding is doubled (I know HDDs are cheep these days, and yet, there are still quite a lot of old or low-end machines in use). If the issue still persists the possibility for it to happen can be reduced but the way I see it at a great cost.

**Comment by ghost** [comment]
@fluxer 
Thanks for supporting explanations.

> Both different kernel versions (which means different versions of the squashfs module) and different squashfs-tools can triggers the problem the way I see it simply because things change and they are not always 100% backwards compatible.

Understood. It can be either case or both.

I will continue try to reproduce this issue, using 12.04 LTS ISO image against 14.04 LTS host system. Based on above discussion, there are four identified variables.
- kernel version of ISO image
- kernel version of host system
- squashfs-tools version of ISO image
- squashfs-tools version of host system

The test cases will be decided and listed later, hopefully in coming weeks.

**Comment by ghost** [comment]
@fluxer 
The "squashfs-tools version of ISO image" is _not_ applicable because remix ISO image doesn't need this package for rebuilding. I checked the output of `apt-cache policy squashfs-tools` on remix system, whose output is `Installed: (none)`.

Earlier, the first case has been completed with details below:

Case 1
12.04 ISO image (kernel 3.2.0.68.81) against;
14.04 host system (kernel 3.13.0.24.28, squashfs-tools 1:4.2+20130409-2)

Test result 1: Failed to reproduce issue; OK

And following are the suggested test cases to be done:

Case 2
12.04 ISO image (kernel 3.2.0.69.82) against;
14.04 host system (same kernel, squashfs-tools as Case 1)

Case 3
12.04 ISO image (kernel 3.13.0.36.31 via linux-generic-lts-trusty) against;
14.04 host system (same kernel, squashfs-tools as Case 1)

Case 4
12.04 ISO image (same kernel as Case 3) against;
14.04 host system (kernel 3.13.0.36.43, same squashfs-tools as Case 1)

The available versions of both kernel and squashfs-tools have been checked after running `apt-get update` today around 18:25 UTC. Testing will be done soon.

**Comment by fluxer** [comment]
@clearkimura Oki doki.

**Comment by ghost** [comment]
@fluxer 
This wee hours of the morning, I finally finished testing above listed above plus one bonus case. Below are test results and its CLI output with uploaded screenshots as proof.

Test result 1: Failed to reproduce issue; OK (as announced earlier)
![ubuntu-i386-12 04-c1](https://cloud.githubusercontent.com/assets/1223304/4522298/180e2e7a-4d26-11e4-9389-e5b55a06a692.png)

Test result 2: Failed to reproduce issue; OK
![ubuntu-i386-12 04-c2](https://cloud.githubusercontent.com/assets/1223304/4522211/dc7c34ca-4d24-11e4-9de6-f741433901a4.png)

Test result 3: Failed to reproduce issue; OK
![ubuntu-i386-12 04-c3](https://cloud.githubusercontent.com/assets/1223304/4522214/e0cdef32-4d24-11e4-88cd-b09a45be0e55.png)

Test result 4: Failed to reproduce issue; OK

The Live session screenshot is same as Test result 3, so screenshot prior to ISO rebuilding is shown.
![c41x-host-iso-compare-c4](https://cloud.githubusercontent.com/assets/1223304/4522286/edc8a33e-4d25-11e4-9faa-837db3d4d393.png)

The host Terminal (top left) and chroot Terminal (bottom right) are shown, after run command `uname -r` to show host system kernel release.

Plus, Test result 5 is a bonus. This is essentially repeated Case 4, except installed with Synaptic package manager and minimal Xfce Desktop environment. This is also meant to test "Archive" and "Desktop" features--works well as expected.

With 12.04 ISO image against 14.04 host system, I couldn't reproduce this issue although had tried with few different kernel releases.

**Comment by fluxer** [comment]
So, everything works like a charm. Can we close this now?

P.S. Thank you very much for testing, Mubiin!

**Comment by ghost** [comment]
Affirmative. Glad to be a help this time!

**Comment by ghost** [comment]
Btw, I forgot to cite one small information while trying to reproduce this issue. The Customizer devel branch which I was using is 4.1.0 (commit 4cda0be), not-so-latest ones.
