### ISSUE TITLE
ISSUE-2013-002 (Desktop button disabled)

### ISSUE THREAD

**Issue by ghost** [clearkimura/Customizer#58]
The **Desktop** button remains disabled, even GUI has been installed.
##### Environment

Unknown
##### Description

In actual case, minimal packages for GNOME 2.30 has been installed on Ubuntu Mini Remix 10.04. Even installation was successful and necessary packages were present on the remix to emulate X-session, the **Desktop** button remains disabled.
##### Workaround

None
##### Solution

Customizer 3.2.3 (3.2.596) is now showing the **Desktop** button enabled as it should, provided that the X-session directory `$WORK_DIR/FileSystem/usr/share/xsessions` is not empty.

Last updated: 2014-02-08

**Comment by ghost** [comment]
To this date, only Ubuntu 10.04 LTS Lucid Lynx is known to have this issue.

**Comment by fluxer** [comment]
No longer relevant, development has moved on.
