### ISSUE TITLE
ISSUE-2013-003 (Failed to test ISO with QEMU)

### ISSUE THREAD

**Issue by ghost** [clearkimura/Customizer#59]
Failed to test rebuilded ISO image after clicking **QEMU** button.
##### Environment

Unknown
##### Description

On 32-bit host system, the command `qemu-system-i386` used by Customizer script doesn’t work. The alternative command `qemu-i386` is valid but failed to emulate the ISO image file either.

On 64-bit host system, this issue is not known. The commands, `qemu-system-x86` and `qemu-x86`, are remain untested.
##### Workaround

Use `qemu` command instead.
##### Solution

To make permanent changes to the script used by Customizer, navigate to `/opt/Customizer/scripts` and open script file named `qemu` in a Text Editor. Go to Line 41 and replace `qemu-system-i386` with `qemu` and save the file.

To save the file, you may need to open and save the changes made to the file as root.

Last updated: 2014-02-08

**Comment by ghost** [comment]
To this date, only Ubuntu 10.04 LTS Lucid Lynx is known to have this issue.

We assumed that other users do not face this problem. Unless we receive a feedback, we will _not_ apply this fix to latest release of Customizer 3.2.3.

**Comment by fluxer** [comment]
Lucid is EOL.
