### ISSUE TITLE
3.2.3 install gui fails on ubuntu mini remix 14.04

### ISSUE THREAD

**Issue by magowiz** [clearkimura/Customizer#65]
Hi,
I downloaded ubuntu mini remix which is on the list of supported ISO, anyway I cannot install a GUI, I choose to install xfce4, it appears a new terminal for some seconds, then it goes away, it does nothing. I had to install it via console issuing apt-get.

Is this a known issue on recent ISO ?

**Comment by magowiz** [comment]
I think I found the issue : the mini remix images comes out with only restricted and main repositories enabled, if I insert also universe and multiverse into sources.list I can install the gui.

**Comment by ghost** [comment]
@magowiz 
It is always a good practice to first review the repositories and update the packages list. This is regardless of you are rebuilding a remix, or whenever you have done a typical installation of Linux distribution.

**Comment by magowiz** [comment]
I see, I only didn't notice the remix version doesn't have universe and multiverse repositories which are needed for installing any gui.
