### ISSUE TITLE
customizer 3.2.3 : cannot install language packs via desktop

### ISSUE THREAD

**Issue by magowiz** [clearkimura/Customizer#67]
If I try, launching the desktop button, to customize installed languages installing missing packages I get :   

org.debian.apt : socket doesn't exist /tmp/aptdaemon-zmjd6wa0/debconf.socket 

which is the right way to install another language and make it default ?

**Comment by ghost** [comment]
@magowiz 
In typical Desktop environment (normal installation users), we all know that we should access the "Language Support" via Control Panel (or System Settings).

However, in chroot environment, what has been known as "right way" isn't necessarily doable.

This issue could be one of the limitations, similar to issue #51 (Some applications don't start in the running X-nested session).

If GUI method doesn't work, there's always a workaround or two (which you can at least try):

##### Method 1

Install language packs via Package Manager (the _Archive_ button), then try to access "Language Support" again via Xephyr (the _Desktop_ button) and see if you can check installed language and set it to default?

##### Method 2

Search language packs via command line (the _Terminal_ button), as in:

```
apt-cache search language-pack
```

Then, install your language packs of choice via command line, as in:

```
sudo apt-get install language-pack-LANG-base
sudo apt-get install language-pack-LANG
```

Replace 'LANG' by the language code of your choice found by running the very first command.
(Original answer:  http://askubuntu.com/a/218396)

If you are unsure which applications has your language support, do check by:

```
check-language-support -l LANG
```

Similarly, replace 'LANG' by the language code of your choice.
(Original answer:  http://askubuntu.com/a/149884)

**Comment by magowiz** [comment]
I see, I was able to install missing language packages via console . I mark this as closed since it is included in known limitations you mentioned.

**Comment by fluxer** [comment]
Just a question from the top of my head: since it's looking for a file in /tmp, what if /tmp was bind-mounted to the chroot /tmp?
