### ISSUE TITLE
Customizer 3.2.3 cannot set locale to "italian"

### ISSUE THREAD

**Issue by magowiz** [clearkimura/Customizer#68]
Running Customizer 3.2.3 gambas3 branch installed via install.sh on Ubuntu 14.04 64-bit host.
 Selected ubuntu-mini-remix-14.04-amd64.iso, 
I changed the settings to use locale "italian" from main->settings Locale, then I selected the iso and let customizer unsquash and prepare the whole environment , if I use "terminal" to run some commands I get :  

[*] Setting up locales
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (italian)

perhaps it should use it_IT instead of "italian"

**Comment by fluxer** [comment]
It seems that Ubuntu is no longer supporting locales aliases. This will be addressed
in the devel branch soon. It will not land in the stable branches, not from me.

**Comment by fluxer** [comment]
Should be done for the devel branch. If Desktop does not launch it's probably
because of rece between the session launched and Xephyr not being started
on time because the generation of locales takes too much time, this should
hopefully be addressed soon.

Can we close this?
