### ISSUE TITLE
Unable to start xephyr

### ISSUE THREAD

**Issue by psycato** [clearkimura/Customizer#7]
Hi,

when trying to run xephyr the following error occurs:

E: Command line option --ensure; is not understood
[!] Chroot has returned exit status

When trying to run package manager (synaptic) the following error message occurs:

E: Command line option ';' [from -f;] is not known.
[!] Chroot has returned exit status

Any quick-fix for this?

**Comment by fluxer** [comment]
Install via the script (https://github.com/fluxer/Customizer/wiki/Install) or wait for the PPA to be updated (could take a few hours), test and report back.

**Comment by psycato** [comment]
It works!

Cheers bud :)

**Comment by fluxer** [comment]
Ok, closing.
