### ISSUE TITLE
Multiple instances are not prevented

### ISSUE THREAD

**Issue by ghost** [clearkimura/Customizer#74]
Running Customizer 4.1.0 (downloaded ZIP as commit 517bc8f) on Xubuntu 14.04 32-bit host.

Initial testing found that Customizer GUI can run multiple instances from separate Terminal, even it shows the same loaded ISO image from first running GUI window.

![screenshot - 09012014 - 123451 am](https://cloud.githubusercontent.com/assets/1223304/4102740/115316ac-313a-11e4-9b77-fd73c2b4bb9c.png)

No major issue when doing this, except "Desktop" feature might be a concern.
-  If the first running GUI executes "Desktop" and followed by another GUI doing the same thing, the currently running Xephyr session will detect duplicates and some errors may be seen.
-  In my case, the first Xephyr session is "overwritten" by another Xephyr session and XFCE notificaton daemon produce error in Xephyr, detecting another daemon trying to run the same configuration.
-  Fortunately, XFCE Notification Area plugin only allows single instance per session, which prevents this issue from getting worse. This issue might get worsen if it was GNOME 2.x. Not sure how GNOME 3.x, MATE or CInnamon handles this yet..

Above all, the master and gambas3 branches doesn't allow multiple instances, as mentioned in issue #38 and older release GUI has warning dialog box to prevent another instance from running.

Shouldn't devel branch follow this exception?

**Comment by fluxer** [comment]
I will look into this soon, thanks for the feedback.
