### ISSUE TITLE
Impossible to login in live-cd created

### ISSUE THREAD

**Issue by gmstyle** [clearkimura/Customizer#75]
Hi guys,
thanks a lot for your work!There is a problem with Customizer 4.1.0 on Ubuntu 14.04.1. it is impossible to login with the iso created (starting from ubuntu-mini-remix 14.04.1 iso). any solution?

gabriele@gabriele-Aspire-5810T:~$ uname -r
3.13.0-35-generic
gabriele@gabriele-Aspire-5810T:~$

thanks a lot again

**Comment by fluxer** [comment]
I will have to investigate the issue as it is something I was not aware of. Will look into it soon.

**Comment by fluxer** [comment]
Just tested with UMR i386 14.04.1 - no issues after rebuild with and without
changes. I can not test the amd64 ISOs, which ISO are you trying to customize
and what changes did you made?

**Comment by gmstyle** [comment]
@fluxer  i try with ubuntu 14.04 (SalentOS 14.04) 32bit and the only changes are made by dist-upgrade command and i removed old kernel leaving the 3.13.0-35-generic one with headers. Now i'm building again the iso with the same changes and when finish i will update you if it works or not.

**Comment by fluxer** [comment]
That's exactly what I hoped to hear - first you report issue against ubuntu-mini-remix 14.04.1
and now you are going to test this against SalentOS 14.04 (never heard of it). If it does
successed you _may_ prove that there is something wrong with UMR but I can not be sure
if that will be the case. SalentOS may have some changes under the hood that affect the
customization process.

Unless you have the same issue with SalentOS and nobody else can replicate the issue I will
have to close it but it will stay open for a while, let's see what happens.

**Comment by gmstyle** [comment]
@fluxer SalentOS is simply an Ubuntu based distro that i develop :) but it not have changes under the hood. the only diffrences between ubuntu are under the desktop environement that is openbox and not unity or others. Live user is salentos like the host. But now i'm waiting to finish the iso rebuild ;)

**Comment by fluxer** [comment]
Good to know. Next time, please, mention this in advance.

**Comment by gmstyle** [comment]
rebuild completed but same issue. impossible to login. i made a screenshot
![error](https://cloud.githubusercontent.com/assets/3391771/4140654/480d521a-33a7-11e4-88a7-30b4f3b2f7b7.png)
i also tried to leave user and host "ubuntu" but same problem

**Comment by fluxer** [comment]
The ISO structure/tree of UMR is quite different from that of Linux Mint for
an example. It's burdens should be carried or it should be fixed in UMR
itself, I'm keen on the second. Unless someone steps in I would rather not
recommend UMR anymore (see issue #70). It has bitten me before a few
times in the past and I'm getting sick of it.

**Comment by gmstyle** [comment]
1st Test:
Starting from SalentOS 14.04 (ubuntu 14.04) iso and only upgrading system with apt-get upgrade the iso was built and it login normally (user and host "salentos"). Kernel is 3.13.0-24 generic and was not upgraded.
Repeat, login in live mode works fine.

2nd Test:
Rebuilding iso from the same SalentOS 14.04 (ubuntu 14.04) iso. NO changes respect the 1st test but simply doing rebuild iso button.
Login failed and error like in the screenshot up.

1-the issue could be random?

**Comment by fluxer** [comment]
I doubt that the issue is random, usually such issues appear when kernel upgrade is made
in chroot. Something is wrong with this capser-thingy and I just can't figure it out.

**Comment by ghost** [comment]
@fluxer 
I do agree that this issue might not be random. Just to recall, we do have similar issue filed under #54 ("Unable to login into the created Live CD/DVD ISO image").

In my experience, this "unable to login" issue is caused by external application i.e. Dropbox that is installed while in chroot.

Which may suggests that, it is not necessarily kernel issue and may have other root cause.

**Comment by ghost** [comment]
@fluxer 
I will try to reproduce this issue soon on my side as well.

Based on above conversation, I should use UMR 14.04 ISO image file (albeit 32 bit for my side) with Customizer 4.1 on 14.04 host system. Then I shall run `dist-upgrade` command and try rebuild it (I will try without Desktop Environment to save rebuild/testing time).

Am I missing anything important?

**Comment by fluxer** [comment]
@clearkimura 

> Which may suggests that, it is not necessarily kernel issue and may have other root cause.

You may be right.

> Am I missing anything important?

No, you are not missing anything.

@gmstyle 
Can we have the packages list from the chroot filesystem? It can help to reproduce
the issue by not just dist-upgrading but also installing the same packages as you.

**Comment by gmstyle** [comment]
@fluxer

I will post it sono. I think tomorrow because now i'm at work. In these days i made some other experiment doing the dame steps with customizer and ubuntu-builder top ( customizer fork).
Made:
1 dist-upgrade
2 removing kernel 3.13.0-24 and leaving 3.13.0-35
3 building ISO

With customizer login fail ( and the upgrading processo was blocked without holding libpam-systemd and others top)

With ubuntu-builder works fine the upgrading process and the login in livello mode

**Comment by fluxer** [comment]
@gmstyle 

> and the upgrading processo was blocked without holding libpam-systemd and others top)

Again on this, in other issue? Have a fix, just read the extended comment carefull:
https://github.com/clearkimura/Customizer/commit/48e7dfd22d87b09ca4d53fd9bf8c5844f7b98f48.

**Comment by ghost** [comment]
@fluxer @gmstyle 
Hm.. I failed to reproduce this issue.

In other words, I can login automatically in live session using the rebuilded ISO from UMR 14.04 32-bit ISO image file. As for Customizer, I had downloaded devel branch (commit https://github.com/clearkimura/Customizer/commit/e2e1db4bc333f15d1921563feb6453fe2dd8cf3b) just before @fluxer pushed updates today.

And I did face the `libpam-systemd` package error after running `apt-get dist-upgrade` command. I lookup on the web and I found the official bug report at [this Launchpad thread](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1325142). The error I have seen looks something like this:

```
Errors were encountered while processing:
 /var/cache/apt/archives/libpam-systemd_204-5ubuntu20.5_i386.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

This package error did two bad things. First, it stopped upgrading subsequent packages which have been downloaded. Second, it prevents me from removing or fixing the dependencies error introduced by the `libpam-systemd` package. Even `apt-get -f install` failed to resolve this error.

As for workaround, the Launchpad thread advice didn't work for me. So I look up for others and found a clue from [this AskUbuntu.com post](http://askubuntu.com/questions/481625/apt-get-upgrade-e-sub-process-usr-bin-dpkg-returned-an-error-code-1), whose answer suggests to edit `/var/lib/dpkg/status` file in a text editor, then delete the whole paragraph that contained the bad package (in our case, "libpam-systemd") and rerun `apt-get dist-upgrade` again to complete the upgrade. It worked for me.

Then I check existing kernel being installed and remove the older ones as @gmstyle did. Output messages have been removed for simplicity.

```
# dpkg --list | grep linux-image
...
# apt-get remove linux-image-3.13.0-24-generic linux-image-extra-3.13.0-24-generic
...
The link /vmlinuz.old is a damaged link
Removing symbolic link vmlinuz.old 
 you may need to re-run your boot loader[grub]
```

Noticed that when I removed the older kernel images, the system warns that user may need to re-run the GRUB boot loader. So I did.

```
# update-grub
```

Exit the chroot Terminal, then proceed to "Rebuild ISO". Rebuilding succeeds and I used VirtualBox to run the rebuilded ISO in my preconfigured machine. I can see the the first boot menu, plymouth, verbose messages being scrolled, then finally leads me to the CLI.

![screenshot - 09072014 - 011832 am](https://cloud.githubusercontent.com/assets/1223304/4175990/8309b6ca-35ef-11e4-9290-cefd4fa47525.png)

As you can see in the screenshot above, the kernel version has been confirmed as `3.13.0-35-generic` via `uname -r` command.

I repeated booting the rebuilded ISO in VirtualBox for three times. I had always able to login automatically in CLI. That's it from my side.

Edit:  Added explanation for workaround file path

**Comment by fluxer** [comment]
@clearkimura 
I said in #63 that it is packaging issue but some people just do not believe it. I'll just have a break.

**Comment by gmstyle** [comment]
Today i made another test always with the same steps. i think that the problem is caused when, after removing old kernel, do not made update-grub. Testing now and always made update-grub after the removing of kernel 3.13.0-24 and login works fine in live mode for me.

When i removed kernel from synaptic in Desktop session (Xephyr) i think i do not made update-grub

@fluxer 

ok thanks for fixing issue #63

**Comment by fluxer** [comment]
@gmstyle 
Yet another packaging issue, if update-grub was triggered on kernel installation that should've happend.
