### ISSUE TITLE
Desktop never run and returned non-zero exit

### ISSUE THREAD

**Issue by ghost** [clearkimura/Customizer#81]
This is another issue found in recent commits of devel branch (not sure since which commit). Below is screenshot showing the error dialog upon clicking **Desktop** button.

![screenshot - 11122014 - 091428 pm-xephyr](https://cloud.githubusercontent.com/assets/1223304/5049151/54c0b250-6c5e-11e4-8176-0e3883938c7f.png)

The Terminal output (as seen in the screenshot):

```
* Running nested X session...
  => Checking
  => Detecting available sessions
  => Session detected: startxfce4
  => Session detected: startxfce4
  => Starting Xephyr
* Unexpected error: global name 'subprocess' is not defined
```

Loaded ISO image is official Xubuntu 14.04 32-bit, using Customizer devel branch (latest commit 92e4b60) on 32-bit host system. The script detects Xfce4 session correctly as expected however, Xephyr window never runs because of unexpected error.

Based on the debug message, apparently the variable name `subprocess` is undefined.

**Comment by fluxer** [comment]
Should be fixed now, I will run lint checks later to see if there are any issues PyLint can catch that I am not aware of.

**Comment by ghost** [comment]
@fluxer 
Voila, it is working now! Tested using latest devel branch (commit ea5d850), with official Xubuntu 14.04 32-bit and own test remix 12.04 32-bit remix ISO images. Both running Xfce4 desktop environment.

Should there be no issues on your side, I think we can close this issue.
